### ISSUE TITLE
"Index was outside the bounds of the array" when no value is provided

### ISSUE THREAD

**Issue by xPaw** [Cysharp/ConsoleAppFramework#109]
```csharp
ConsoleApp.Run(args, (int foo) => Console.WriteLine($"Foo: {foo}"));
```

Command: `./cmd --foo`

This also makes me think the unchecked `args[++i]` would eat next argument.

For parameters that require a value, it should say so.

**Comment by neuecc** [comment]
thanks! I've fixed in v5.0.1!
