### ISSUE TITLE
Do not print the stack trace for `ArgumentException`

### ISSUE THREAD

**Issue by xPaw** [Cysharp/ConsoleAppFramework#112]
Since it's being thrown by the generated code and is expected to be visible by the user, I don't think the stacktrace provides any value.

Current:
```
System.ArgumentException: Argument '-abc' does not found in command prameters.
   at ConsoleAppFramework.ConsoleApp.ThrowArgumentNameNotFound(String argumentName) in ConsoleApp.cs:line 110
   at ConsoleAppFramework.ConsoleApp.Run(String[] args, Func`15 command) in ConsoleApp.Run.g.cs:line 242
```

Suggestion:
```
Argument '-abc' does not found in command prameters.
```

**Comment by neuecc** [comment]
Thank you. I cannot give ArgumentException special treatment, so I plan to change the exception being thrown to a custom one (ParseFailedException?) and modify it to only output the message!

**Comment by neuecc** [comment]
v5.1.1 throws ArgumentParseFailedException and only shows message.
