### ISSUE TITLE
The source generation is non-incremental

### ISSUE THREAD

**Issue by PaulusParssinen** [Cysharp/ConsoleAppFramework#114]
The source generation is completely non incremental due to rooting of compilation objects. There should not be `*Syntax` or symbol instances in the compilation pipeline, as they completely break the caching and increase memory usage. It's important to establish a value type data model of the things required for generating the source, see more [here](https://andrewlock.net/creating-a-source-generator-part-9-avoiding-performance-pitfalls-in-incremental-generators/#3-use-a-value-type-data-model-or-records-or-a-custom-comparer-).

https://github.com/Cysharp/ConsoleAppFramework/blob/48d550c2cc476b5773673b093c1678b46319dbdd/src/ConsoleAppFramework/ConsoleAppGenerator.cs#L39
and 
https://github.com/Cysharp/ConsoleAppFramework/blob/48d550c2cc476b5773673b093c1678b46319dbdd/src/ConsoleAppFramework/ConsoleAppGenerator.cs#L63-L66

Many libraries fall into this pit of failure. See similar issues in many other libraries that used `IIncrementalGenerator` in correctly:
- https://github.com/zompinc/sync-method-generator/issues/20
- https://github.com/dotnet/winforms/issues/8386
- https://github.com/k94ll13nn3/AutoConstructor/issues/82
- https://github.com/DevTeam/Pure.DI/issues/39
and many many more.

Related Roslyn issues:
- https://github.com/dotnet/roslyn/issues/71629

Here's solid article from Andrew Lock about the issues: https://andrewlock.net/creating-a-source-generator-part-9-avoiding-performance-pitfalls-in-incremental-generators/

You can see here how one library fixed their incremental generator: https://github.com/k94ll13nn3/AutoConstructor/pull/83

It is also possible to add tests to test whether a pipeline is incremental: 
- https://andrewlock.net/creating-a-source-generator-part-10-testing-your-incremental-generator-pipeline-outputs-are-cacheable/
- https://github.com/k94ll13nn3/AutoConstructor/blob/main/tests/AutoConstructor.Tests/IncrementalGeneratorTests.cs

**Comment by neuecc** [comment]
Thank you for the wealth of useful information!
I will attempt to make corrections based on the information you have provided!
