### ISSUE TITLE
Allow type arguments

### ISSUE THREAD

**Issue by xPaw** [Cysharp/ConsoleAppFramework#121]
This would allow using readonly fields in the class. Currently to do this I think I would need to have a method to accept the arguments, and then duplicate them in the class.

I'm thinking something like this:
```
        public static void Main(string[] args)
        {
            var appInstance = ConsoleApp<App>.Run(args);
        }

        public class App
        {
            /// <summary>
            /// Test app.
            /// </summary>
            /// <param name="foo">A</param>
            /// <param name="bar">B</param>
            public App(int foo, int bar)
            {
                Console.WriteLine(foo + bar);
            }
        }
```

Is this a reasonable idea?

**Comment by neuecc** [comment]
I don't understand what you want to do; readonly fields?

**Comment by xPaw** [comment]
I want to pass a constructor instead of method into Run() so that it creates an instance of a class

**Comment by neuecc** [comment]
Okay, I don't think it's a good idea, so I can't adopt that idea.
If you want a return value, you can pass it out through a closure or something.

```csharp
Foo foo = default!;
ConsoleApp.Run(args, (int x, int y) => 
{
    foo = new Foo();
});

Console.WriteLine(foo);
```

**Comment by xPaw** [comment]
I don't really want the return value, but rather for the parsed arguments to be passed into the constructor.
