### ISSUE TITLE
v5 work only net 8?

### ISSUE THREAD

**Issue by KANekT** [Cysharp/ConsoleAppFramework#122]
v5 work only net 8?

but in nuget is empty https://www.nuget.org/packages/ConsoleAppFramework#supportedframeworks-body-tab

example for https://www.nuget.org/packages/Cocona#supportedframeworks-body-tab

**Comment by neuecc** [comment]
ConsoleAppFramework is analyzer(Source Generator) only project.
However generated code is dependent on .NET 8(using new types of .NET 8)
