### ISSUE TITLE
Feature request: Separate package from ConsoleAppFramework.Host

### ISSUE THREAD

**Issue by pomianowski** [Cysharp/ConsoleAppFramework#127]
# Proposal
Create a simple builder pattern in a separate package to make building a console application using DI easier.

## Sample

```csharp
// ConsoleAppFramework.Host / ConsoleAppFramework.DependencyInjection
ConsoleAppHostBuilder builder = ConsoleApp.CreateHostBuilder(args);
builder.Services.AddSingleton<DbContext>();
builder.Services.AddStackExchangeRedisCache();
builder.Configuration["OpenTelemetryServiceOptions:ServiceVersion"] = Assembly.InformationalVersion;

ConsoleApp app = builder.Build();
app.AddCommands<ConsoleCommands>();
await app.StartAsync(args);
```

**Comment by neuecc** [comment]
I thought about that at first too.
However, in terms of the number of lines, it's not much different from inserting it into the ServiceProvider.
So I don't really think it's become that much easier.
Considering that, I think the drawback of adding a custom type outweighs the benefits.
