### ISSUE TITLE
[Question] Dependent - Attribute Based Validations?

### ISSUE THREAD

**Issue by Simonl9l** [Cysharp/ConsoleAppFramework#143]
Per the Readme [section](https://github.com/Cysharp/ConsoleAppFramework/tree/master#attribute-based-parameters-validation) on this, is there a way to create a custom validation that can validate based on the value of another option/argument? 

Is there an example, or could the documentation be updated to demonstrate this?

There is potential and example [here](https://stackoverflow.com/questions/2280539/custom-model-validation-of-dependent-properties-using-data-annotations) that validates across properties of a class, but given that this Framework does not use class for the Options/Arguments but method parameters, I'm not sure how this can work.

**Comment by neuecc** [comment]
If you implement `ValidationAttribute`, it will work without any issues.
This is not specific to this framework, but a general approach, so please research it on your own.
