### ISSUE TITLE
[Question] Completion Support?

### ISSUE THREAD

**Issue by Simonl9l** [Cysharp/ConsoleAppFramework#145]
Some CLI frameworks also offer completion support, where they will generate a completion file that can be used by the requisite shell to support command completions.

https://en.wikipedia.org/wiki/Command-line_completion

Are there an future plans to support this ?

**Comment by neuecc** [comment]
We have no intention of supporting that.
In that case, it would be better to use a different framework.

**Comment by SapiensAnatis** [comment]
I understand it is a big ask to add support for this especially if it needs to be cross-platform. I wrote quite [a small program](https://gist.github.com/SapiensAnatis/396af4467256e9ae82d07fdc6ebbe985) to generate a Bash completion script using the `GetCliSchema` method that was recently added. It works to auto-complete commands and options but not option or argument values, and there are probably edge cases or features I'm missing support for. 

Perhaps this could work as a third-party package?
