### ISSUE TITLE
[Question] Support for Object binding and ConsoleApp configuration for Code Generated Serialize - JsonSerializerContext?

### ISSUE THREAD

**Issue by Simonl9l** [Cysharp/ConsoleAppFramework#146]
Today it seem that serialization options can be provided via `ConsoleApp.JsonSerializerOptions`, and this is used when deserializing `Object` bindings?

Given the code generated nature and implicit support for AoT, it also seems sensible to support Code Generated Serializers and specifically `JsonSerializerContext`. Is it intended to configure this like so:

```C#
 ConsoleApp.JsonSerializerOptions = new JsonSerializerOptions
  {
     TypeInfoResolverChain = { MyOptionsSerializerContext.Default }
  };
```
I'm not sure if this generated code, actually leverages the code generates serializer:
```C#
try { arg0 = System.Text.Json.JsonSerializer.Deserialize<global::MyOptions>(args[++i], JsonSerializerOptions); } catch { ThrowArgumentParseFailed("options", args[i]); }
arg0Parsed = true;
break;
```
I'd expect it more to be:
```C#
try { arg0 = System.Text.Json.JsonSerializer.Deserialize(args[++i], MyOptionsSerializerContext.Default.MyOptions); } catch { ThrowArgumentParseFailed("options", args[i]); }
arg0Parsed = true;
break;
```

**Comment by neuecc** [comment]
If you set it in JsonSerializerOptions, any JsonSerializerContext will be used.
I don't think there's any problem with that.
