### ISSUE TITLE
[Feature Request] Adding the Commands Class to the service Container to enable access to it from other services via DI?

### ISSUE THREAD

**Issue by Simonl9l** [Cysharp/ConsoleAppFramework#148]
Is is correct that the following construct:
```C#
ConsoleApp.ServiceProvider = services.BuildServiceProvider();
var app = ConsoleApp.Create();
app.Add<MyCommands>();
```
 and specifically `app.Add<MyCommands>()` is just a code signature the code generator runs on as the implementation of the resultant `ConsoleApp.Add<T>()` is empty:

```C#
public void Add<T>() { }
```

In the case that one is using DI, is it not unrealistic that a registered service might want to interact with the command class via an interface that could be injected into it?

Today is seem the code just `new`'s up the Commands class (getting services from the DI container) and calls the requisite public function. 

Could and alternative approach be to register the Command Class as say a Singleton (say), and any interfaces on it that one wants to leverage from other services. 

```C#
services.AddSingleton<IMyService, MyService>();
services.AddSingleton<MyCommandClass>();
services.AddSingleton<IMyInterface>(provider => provider.GetRequiredService<MyCommandClass>());
```
And then I the generated use the `ConsoleApp.ServiceProvider` to instantiate the the Command Class (potentially updating [these](https://github.com/Cysharp/ConsoleAppFramework/blob/d5fb93ae3b408b9ed50866a3e83dbf58ea4c416a/src/ConsoleAppFramework/Emitter.cs#L264C1-L273C22) lines in the `Emitter.cs` - assuming the parser has the requisite information):
```C#
...
 var instance = ServiceProvider!.GetRequiredService<global::MyCommandClass>();
...
```
The DI container will the inject the required services as needed based the constructor, and invoke the Command Function as before.
 
Also a potential advantage on registering and getting the Command Class back from the DI Container, is that is will (from Net8.0) handle Async/Disposal in the container - not that the library has not already solved for that otherwise - in a non DI way.

**Comment by neuecc** [comment]
`Add<T>` is probably necessary to pass type information to the Source Generator.
It may be possible to make a change that prioritizes the Service Provider in instantiation.

```csharp
var instance = provider.GetService<MyCommands>() ?? new MyCommands(); /* when T is concrete class, fallback */
```

If this satisfies your needs, I will consider implementing it.

**Comment by neuecc** [comment]
Hmm, by the way, are you actually struggling with this in a real-world case?
These kinds of things often involve design trade-offs, so it's not advisable to unnecessarily add complexity just because it seems theoretically correct.

**Comment by neuecc** [comment]
To be honest, I don't understand more than half of what's being said.
As a result, I don't think any of the priorities are particularly high.
