### ISSUE TITLE
[Question] Add a list of projects that are using ConsoleAppFramework?

### ISSUE THREAD

**Issue by patricktcoakley** [Cysharp/ConsoleAppFramework#152]
Hi, I would like to ask if adding a list of open-source projects using ConsoleAppFramework to the docs would be a reasonable request. I think it would be nice to have some reference examples in the real world using the library instead of just the examples in the README, and it would also make it easier for new people to see what kinds of projects are using it.

Thoughts?

**Comment by patricktcoakley** [comment]
Yeah I spent some time looking through a bunch of these but many of them didn't have much code using the library.  It was more of a suggestion to help new users learn more by example since sometimes the documentation can be a bit confusing at times. Not a big deal, feel free to close this.

**Comment by neuecc** [comment]
Yes, I understand how you feel.

**Comment by Athari** [comment]
The [dependents](https://github.com/Cysharp/ConsoleAppFramework/network/dependents) list has the downside of not being sortable, so getting to any remotely relevant projects is tedious.

What's most amusing is that the most starred projects seem to be @neuecc's own. 😁 And the second most starred category seems to be game modding tools.
