### ISSUE TITLE
.NET 9 marks TrySplitParse as not AOT safe.

### ISSUE THREAD

**Issue by Mpdreamz** [Cysharp/ConsoleAppFramework#154]
```sharp
    static bool TrySplitParse<T>(ReadOnlySpan<char> s, out T[] result)
       where T : ISpanParsable<T>
    {
        if (s.StartsWith("["))
        {
            try
            {
                result = System.Text.Json.JsonSerializer.Deserialize<T[]>(s, JsonSerializerOptions)!;
                return true;
```

Starting with .NET 9 this now yields the following compiler errors.

> ConsoleApp.cs(192,26): Error IL2026 : Using member 'System.Text.Json.JsonSerializer.Deserialize<TValue>(ReadOnlySpan<Char>, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.
> ConsoleApp.cs(192,26): Error IL3050 : Using member 'System.Text.Json.JsonSerializer.Deserialize<TValue>(ReadOnlySpan<Char>, JsonSerializerOptions)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation. Use System.Text.Json source generation for native AOT applications.
```

**Comment by neuecc** [comment]
Oh, thanks, I'll check soon.

**Comment by neuecc** [comment]
fixed in `v5.3.2`.

**Comment by neuecc** [comment]
still occurs errro, need more fix.

**Comment by neuecc** [comment]
The warnings have been disabled at the code level.
When deserializing custom objects in NativeAOT, runtime exceptions will occur.
This seems to be a limitation of the current JsonSerializer design, and this is also the case with WebAPI NativeAOT templates, where some warnings are disabled.

In most cases, it should work fine even with NativeAOT, and when runtime exceptions occur, they can be avoided by setting Source Generated JsonSerializerOptions. I consider this to be a reasonable countermeasure.
