### ISSUE TITLE
Is it possible to have optional parameters?

### ISSUE THREAD

**Issue by yatagarasu25** [Cysharp/ConsoleAppFramework#36]
Have a command which can accept one or two parameters, 
Now if I have it declared like
`public async Task Cmd([Option(0)] string p1, [Option(1)] string p2)`
it complains that I need two parameters. Can I mark second parameter optional somehow?

upd: Found a solution, declaring an overload with one parameter solves the problem
`public async Task Cmd([Option(0)] string p1)`

Don't know if that is official supported way.

upd:
That approach produce several help lines in the output.

**Comment by mayuki** [comment]
If the parameter of a method is/are optional, the parameter is treated as an optional command argument.

```csharp
public async Task Cmd([Option(0)] string p1, [Option(1)] string p2 = "DefaultValue")
{
    Console.WriteLine($"p1={p1}; p2={p2}");
}
```

```
$ dotnet run -- foo
p1=foo; p2=DefaultValue
```

**Comment by yatagarasu25** [comment]
Thanks, my approach produce several help lines in the output. Maybe that should also be fixed.
