### ISSUE TITLE
Any way how to implement sub commands?

### ISSUE THREAD

**Issue by yatagarasu25** [Cysharp/ConsoleAppFramework#37]
Need to implement nested commands, something like 

`program.exe command subcommand1`
`program.exe command subcommand2`
etc.

Any way how to implement it?

One way that can be possibly implemented by having `[Command("command subcommand1")]` but that does not work now.

**Comment by kt81** [comment]
@yatagarasu25 
https://github.com/Cysharp/ConsoleAppFramework#multi-batch-application
This seems to work for your case

**Comment by yatagarasu25** [comment]
@kt81 not exactly what i want. The syntax is not convenient, but maybe that is a start in a good direction. If it could be somehow customized - ex. [Command("command")] attribute to a class and no dot syntax.
