### ISSUE TITLE
RunConsoleAppFrameworkAsync method only searches ConsoleApp from loaded assemblies

### ISSUE THREAD

**Issue by nguyenvuduc** [Cysharp/ConsoleAppFramework#38]
The document of `RunConsoleAppFrameworkAsync` method says "Run multiple ConsoleApp that are searched from all assemblies". However, when I looked at `GetConsoleAppTypes` method, it actually only search in assemblies returned by `AppDomain.CurrentDomain.GetAssemblies()`. The `GetAssemblies` method returns only loaded assemblies.

Currently, to workaround this, I have to reference a type of target assemblies or force them to be loaded before calling `RunConsoleAppFrameworkAsync` method.

**Comment by yatagarasu25** [comment]
That makes sense, anyway you'll need to load an assembly before you get it's contents.
I wonder if there is dynamic loading/unloading routines, that may be handy.

**Comment by neuecc** [comment]
This problem is common in assembly retrieval frameworks.
I'm hoping you have some good ideas.

There are solutions like this, but they are exaggerated.
https://github.com/Fody/LoadAssembliesOnStartup

**Comment by nguyenvuduc** [comment]
I think the RunConsoleAppFrameworkAsync is very useful or multi modules application.

However, it should have a parameter that accept a list of assemblies that it will search for ConsoleApp. This is to make the result of the method to be more deterministic.
Otherwise, other developers might think it is a bug when they realize some of their ConsoleApp are not loaded.

**Comment by neuecc** [comment]
`public static Task RunConsoleAppFrameworkAsync(this IHostBuilder hostBuilder, string[] args, IConsoleAppInterceptor? interceptor = null, Assembly[] searchAssemblies = null)`
Is this okay?

**Comment by nguyenvuduc** [comment]
Hi @neuecc,
Yes, I think it is good.
