### ISSUE TITLE
パラメータバインディングに失敗する

### ISSUE THREAD

**Issue by hygehyge** [Cysharp/ConsoleAppFramework#46]
便利に使わさせていただいています。
Ver.2.4.0に更新したところ、標記の問題が出たので相談させて下さい。

```C#
ConsoleApp1.exe
Usage: ConsoleApp1 <str> [options...]

Arguments:
  [0] <String>    str

Options:
  -b, -p_bool <Boolean>    bool (Default: False)
```

となっている際に、実行結果が下記のようになってしまいます。
(-bがバインドされない)

```C#
ConsoleApp1.exe "input" -b true
str:input, bool:True

ConsoleApp1.exe "input" -b false
str:input, bool:True

ConsoleApp1.exe "input" -b True
str:input, bool:True

ConsoleApp1.exe "input" -b False
str:input, bool:True
```

Ver.2.0.2では起きないようです。
下記が再現ソースです。
[ConsoleApp1.zip](https://github.com/Cysharp/ConsoleAppFramework/files/4961122/ConsoleApp1.zip)

お手数ですが、確認をお願いします。

**Comment by neuecc** [comment]
返信が大変遅れて失礼しました。
実際デグレだったので、v3.0で修正しました、報告ありがとうございます！
