### ISSUE TITLE
Proposal: Boolean option legend should not show its value type

### ISSUE THREAD

**Issue by yfakariya** [Cysharp/ConsoleAppFramework#52]
Currently, `bool` typed options are shown in help message like `-o, --option <Boolean>  (description...)`. It looks that specifying boolean value is required despite it is omittable (we can specify the option with `-o` only in above example). Many users cannot notice this fact. So, it is better to suppress `<Boolean>`, such as `-o, --option  (description...)` for previous example, when all following conditions are met:

* The option is optional (has default value).
* The default value is `false`.

**Comment by neuecc** [comment]
I think you're right.
Also, bool will always be changed to optional (default false) (except when =true).
