### ISSUE TITLE
Add a way to specify the default value

### ISSUE THREAD

**Issue by dbuksbaum** [Cysharp/ConsoleAppFramework#54]
Currently the default value is taken directly from the method syntax [void Run(int foo = 0)] would yield the default value of 0 in the help message. However, some types can be easily defined as a default, such as DateTime?. In these cases, the null value is checked, and if there, a value is assigned.

So, a method syntax of: void Run(DateTime? date = null) currently shows null, but the actual default is set to DateTime.Today if the value is null. 

Can the Options attribute be modified to take an alternative text, or maybe a Default attribute used to override the default behavior?

**Comment by neuecc** [comment]
Thank you, good suggestion.
I'll add alt text property to option -  `[Option(..., DefaultValue = "DateTime.Today")]`.
This is what you want, isn't it?

**Comment by dbuksbaum** [comment]
Thats sounds like a good solution.

Thanks

**Comment by neuecc** [comment]
I've released `3.2.0`, it includes this feature.
