### ISSUE TITLE
How can I handle white-space in JSON

### ISSUE THREAD

**Issue by ytabuchi** [Cysharp/ConsoleAppFramework#63]
How can I use white-space in JSON?
The sample parameters in the document, https://github.com/Cysharp/ConsoleAppFramework#complex-argument ,
```> SampleApp.exe -array [10,20,30] -person {\"Age\":10,\"Name\":\"foo\"}``` 
works well from Windows CMD, but
```> SampleApp.exe -array [10,20,30] -person {\"Age\":10,\"Name\":\"foo bar\"}``` 
will return the error below: 
```Parameter "person" fail on JSON deserialize, please check type or JSON escape or add double-quotation. args: -array [10,20,30] -person {"Age":10,"Name":"foo bar"}```

Please tell me a solution.

**Comment by neuecc** [comment]
require non escape double quotation.
`> SampleApp.exe -array [10,20,30] -person "{\"Age\":10,\"Name\":\"foo bar\"}"`

**Comment by neuecc** [comment]
Indeed, this ReadMe is a naive statement and a very poor example. I will fix it, thanks.

**Comment by ytabuchi** [comment]
I got it! Thank you!!!
なるほど！ありがとうございます！！！
