### ISSUE TITLE
Change usage name

### ISSUE THREAD

**Issue by mdnapo** [Cysharp/ConsoleAppFramework#84]
Is there any way to change the usage name, besides renaming your project?
![image](https://user-images.githubusercontent.com/7224020/180092569-2a5715da-1ea0-4f79-b079-dd67f9a4f3e0.png)
To be more specific I'd like to replace `Retrospect.CLI` in the image above with something else.

**Comment by neuecc** [comment]
Default is `Path.GetFileNameWithoutExtension(Assembly.GetEntryAssembly()!.Location);`
and can not configure it.
I think good to add change usage name option to `ConsoleAppOptions`, thanks.

**Comment by neuecc** [comment]
I've released 4.2.2, it has ConsoleAppOptions.ApplicationName to configure it.
