### ISSUE TITLE
Global filters with dependency injection

### ISSUE THREAD

**Issue by wozzo** [Cysharp/ConsoleAppFramework#88]
The [documentation](https://github.com/Cysharp/ConsoleAppFramework#filter) specifies⬇️
>  // Filter is instantiated by DI so you can get parameter by constructor injection.

But only shows how to add global filters where the instance is instantiated upfront
```csharp
var app = ConsoleApp.Create(args, options =>
{
    options.GlobalFilters = new ConsoleAppFilter[]
    {
        new MutextFilter() { Order = -9999 } ,
        new LogRunningTimeFilter() { Oder = -9998 }, 
    }
});
```
Is there a way to use Dependency Injection with global filters, that I've just missed from the documentation?

e.g.

```csharp
// filter class
public class MyFilter : ConsoleAppFilter
{
  private readonly ILogger<MyFilter> logger;
  public MyFilter(ILogger<MyFilter> logger)
  {
    this.logger = logger;
  }

  public override async ValueTask Invoke(ConsoleAppContext context, Func<ConsoleAppContext, ValueTask> next)
  {
    logger.LogInformation(context.MethodInfo.Name);
    await next(context);
  }
}

// and adding the filter
var builder = ConsoleApp.CreateBuilder(args, options =>
  {
    options.AddFilter<MyFilter>;
  });

**Comment by wozzo** [comment]
Still a thing

**Comment by neuecc** [comment]
Sorry for delayed response, I'll check it.

**Comment by LadislavBohm** [comment]
I don't think you can create them out of the box with DI but do you need to? ConsoleAppContext has access to ServiceProvider so you can resolve dependencies there.
